site_name: Meus Tutoriais
site_url: "https://dpanegassi.github.io/mkdocs/"


theme:
  name: material
  palette:
    primary: blue grey
    accent: blue
  font:
    code: Roboto Mono
  favicon: images/favicon.png
  features:
    - tabs
    - instant

    
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:  # better code, instead of CodeHilite
      #linenums:          true
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Arvore de Pa«µinas
nav:
  - Home:
    - Sobre: index.md
  - GitLab:
    - Instalando MkDocs: gitlab/gitlab.md
    - Exemplos Markdown: gitlab/exemplos.md
    
