# This is a basic workflow to help you get started with Actions

name: Deploy automático do mkdocs após commit na master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build do MkDocs
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout master
        uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Build mkdocs
        uses: dpanegassi/dpanegassi.github.io@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
